# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\vadim.zubarev\Documents\Polytech\Dubrovskiy\CLang\project\real-car-adas-monitor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\vadim.zubarev\Documents\Polytech\Dubrovskiy\CLang\project\real-car-adas-monitor\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vadim.zubarev\Documents\Polytech\Dubrovskiy\CLang\project\real-car-adas-monitor\build\CMakeFiles C:\Users\vadim.zubarev\Documents\Polytech\Dubrovskiy\CLang\project\real-car-adas-monitor\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vadim.zubarev\Documents\Polytech\Dubrovskiy\CLang\project\real-car-adas-monitor\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RealCarMonitor

# Build rule for target.
RealCarMonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RealCarMonitor
.PHONY : RealCarMonitor

# fast build rule for target.
RealCarMonitor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/build
.PHONY : RealCarMonitor/fast

#=============================================================================
# Target rules for targets named RunTests

# Build rule for target.
RunTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RunTests
.PHONY : RunTests

# fast build rule for target.
RunTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RunTests.dir\build.make CMakeFiles/RunTests.dir/build
.PHONY : RunTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock_main.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest_main.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/dashboard.obj: src/dashboard.cpp.obj
.PHONY : src/dashboard.obj

# target to build an object file
src/dashboard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dashboard.cpp.obj
.PHONY : src/dashboard.cpp.obj

src/dashboard.i: src/dashboard.cpp.i
.PHONY : src/dashboard.i

# target to preprocess a source file
src/dashboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dashboard.cpp.i
.PHONY : src/dashboard.cpp.i

src/dashboard.s: src/dashboard.cpp.s
.PHONY : src/dashboard.s

# target to generate assembly for a file
src/dashboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dashboard.cpp.s
.PHONY : src/dashboard.cpp.s

src/dms_hud.obj: src/dms_hud.cpp.obj
.PHONY : src/dms_hud.obj

# target to build an object file
src/dms_hud.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_hud.cpp.obj
.PHONY : src/dms_hud.cpp.obj

src/dms_hud.i: src/dms_hud.cpp.i
.PHONY : src/dms_hud.i

# target to preprocess a source file
src/dms_hud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_hud.cpp.i
.PHONY : src/dms_hud.cpp.i

src/dms_hud.s: src/dms_hud.cpp.s
.PHONY : src/dms_hud.s

# target to generate assembly for a file
src/dms_hud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_hud.cpp.s
.PHONY : src/dms_hud.cpp.s

src/dms_monitor.obj: src/dms_monitor.cpp.obj
.PHONY : src/dms_monitor.obj

# target to build an object file
src/dms_monitor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_monitor.cpp.obj
.PHONY : src/dms_monitor.cpp.obj

src/dms_monitor.i: src/dms_monitor.cpp.i
.PHONY : src/dms_monitor.i

# target to preprocess a source file
src/dms_monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_monitor.cpp.i
.PHONY : src/dms_monitor.cpp.i

src/dms_monitor.s: src/dms_monitor.cpp.s
.PHONY : src/dms_monitor.s

# target to generate assembly for a file
src/dms_monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/dms_monitor.cpp.s
.PHONY : src/dms_monitor.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/obd_parser.obj: src/obd_parser.cpp.obj
.PHONY : src/obd_parser.obj

# target to build an object file
src/obd_parser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/obd_parser.cpp.obj
.PHONY : src/obd_parser.cpp.obj

src/obd_parser.i: src/obd_parser.cpp.i
.PHONY : src/obd_parser.i

# target to preprocess a source file
src/obd_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/obd_parser.cpp.i
.PHONY : src/obd_parser.cpp.i

src/obd_parser.s: src/obd_parser.cpp.s
.PHONY : src/obd_parser.s

# target to generate assembly for a file
src/obd_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/obd_parser.cpp.s
.PHONY : src/obd_parser.cpp.s

src/onnx_classifier.obj: src/onnx_classifier.cpp.obj
.PHONY : src/onnx_classifier.obj

# target to build an object file
src/onnx_classifier.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/onnx_classifier.cpp.obj
.PHONY : src/onnx_classifier.cpp.obj

src/onnx_classifier.i: src/onnx_classifier.cpp.i
.PHONY : src/onnx_classifier.i

# target to preprocess a source file
src/onnx_classifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/onnx_classifier.cpp.i
.PHONY : src/onnx_classifier.cpp.i

src/onnx_classifier.s: src/onnx_classifier.cpp.s
.PHONY : src/onnx_classifier.s

# target to generate assembly for a file
src/onnx_classifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RealCarMonitor.dir\build.make CMakeFiles/RealCarMonitor.dir/src/onnx_classifier.cpp.s
.PHONY : src/onnx_classifier.cpp.s

tests/test_obd_parser.obj: tests/test_obd_parser.cpp.obj
.PHONY : tests/test_obd_parser.obj

# target to build an object file
tests/test_obd_parser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RunTests.dir\build.make CMakeFiles/RunTests.dir/tests/test_obd_parser.cpp.obj
.PHONY : tests/test_obd_parser.cpp.obj

tests/test_obd_parser.i: tests/test_obd_parser.cpp.i
.PHONY : tests/test_obd_parser.i

# target to preprocess a source file
tests/test_obd_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RunTests.dir\build.make CMakeFiles/RunTests.dir/tests/test_obd_parser.cpp.i
.PHONY : tests/test_obd_parser.cpp.i

tests/test_obd_parser.s: tests/test_obd_parser.cpp.s
.PHONY : tests/test_obd_parser.s

# target to generate assembly for a file
tests/test_obd_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RunTests.dir\build.make CMakeFiles/RunTests.dir/tests/test_obd_parser.cpp.s
.PHONY : tests/test_obd_parser.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... RealCarMonitor
	@echo ... RunTests
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
	@echo ... src/dashboard.obj
	@echo ... src/dashboard.i
	@echo ... src/dashboard.s
	@echo ... src/dms_hud.obj
	@echo ... src/dms_hud.i
	@echo ... src/dms_hud.s
	@echo ... src/dms_monitor.obj
	@echo ... src/dms_monitor.i
	@echo ... src/dms_monitor.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/obd_parser.obj
	@echo ... src/obd_parser.i
	@echo ... src/obd_parser.s
	@echo ... src/onnx_classifier.obj
	@echo ... src/onnx_classifier.i
	@echo ... src/onnx_classifier.s
	@echo ... tests/test_obd_parser.obj
	@echo ... tests/test_obd_parser.i
	@echo ... tests/test_obd_parser.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

